"""Public, topology-neutral interaction contracts and kernel."""

from .callbacks import (
    CallbackRegistry,
    CallbackResolution,
    CallbackStore,
    SQLiteCallbackStore,
)
from .conformance import AdapterCheckResult, MethodCheck, check_adapter
from .contracts import (
    BubbleRequest,
    CallbackPayload,
    CallbackRejection,
    CallbackToken,
    ChoiceOption,
    ChoicesRequest,
    CompletionMode,
    DeliveryStatus,
    IncomingReactionChange,
    IncomingReactionCount,
    IncomingSticker,
    IncomingStickerEvent,
    InteractionCapabilities,
    InteractionHost,
    InteractionKind,
    InteractionReceipt,
    MiniAppHost,
    MiniAppRequest,
    ReactionAcceptance,
    ReactionActor,
    ReactionCount,
    ReactionRejection,
    ReactionRequest,
    ReactionType,
    ReactionValue,
    RegularSticker,
    RichReply,
    RichReplyReceipt,
    StickerFormat,
    StickerModelView,
    StickerPart,
    StickerPartKind,
    StickerRequest,
    StickerType,
    TargetRef,
    TransportReceipt,
)
from .kernel import InteractionKernel
from .plans import (
    PLAN_VERSION,
    ActionPlanError,
    BubblePlanAction,
    ChoicesPlanAction,
    InteractionPlan,
    PlanContext,
    ReactionPlanAction,
    StickerPlanAction,
    action_plan_to_reply,
    bind_interaction_plan,
    parse_interaction_plan,
)
from .stickers import (
    SQLiteStickerCatalog,
    StickerCatalog,
    ingest_incoming_sticker,
    sticker_catalog_id,
)
from .text import split_semantic_bubbles

__version__ = "0.1.0"

__all__ = [
    "ActionPlanError",
    "AdapterCheckResult",
    "BubbleRequest",
    "BubblePlanAction",
    "CallbackPayload",
    "CallbackRegistry",
    "CallbackRejection",
    "CallbackStore",
    "CallbackResolution",
    "CallbackToken",
    "ChoiceOption",
    "ChoicesRequest",
    "ChoicesPlanAction",
    "CompletionMode",
    "DeliveryStatus",
    "IncomingReactionChange",
    "IncomingReactionCount",
    "IncomingSticker",
    "IncomingStickerEvent",
    "InteractionCapabilities",
    "InteractionHost",
    "InteractionKernel",
    "InteractionKind",
    "InteractionReceipt",
    "InteractionPlan",
    "MiniAppHost",
    "MiniAppRequest",
    "MethodCheck",
    "PLAN_VERSION",
    "PlanContext",
    "ReactionAcceptance",
    "ReactionActor",
    "ReactionCount",
    "ReactionPlanAction",
    "ReactionRejection",
    "ReactionRequest",
    "ReactionType",
    "ReactionValue",
    "RegularSticker",
    "RichReply",
    "RichReplyReceipt",
    "SQLiteCallbackStore",
    "SQLiteStickerCatalog",
    "StickerCatalog",
    "StickerFormat",
    "StickerModelView",
    "StickerPlanAction",
    "StickerPart",
    "StickerPartKind",
    "StickerRequest",
    "StickerType",
    "TargetRef",
    "TransportReceipt",
    "action_plan_to_reply",
    "bind_interaction_plan",
    "check_adapter",
    "ingest_incoming_sticker",
    "parse_interaction_plan",
    "split_semantic_bubbles",
    "sticker_catalog_id",
]
