"""Public, topology-neutral interaction contracts and kernel."""

from .callbacks import (
    CallbackRegistry,
    CallbackResolution,
    CallbackStore,
    SQLiteCallbackStore,
)
from .contracts import (
    BubbleRequest,
    CallbackPayload,
    CallbackRejection,
    CallbackToken,
    ChoiceOption,
    ChoicesRequest,
    CompletionMode,
    DeliveryStatus,
    IncomingReaction,
    IncomingSticker,
    InteractionCapabilities,
    InteractionHost,
    InteractionKind,
    InteractionReceipt,
    MiniAppHost,
    MiniAppRequest,
    ReactionRequest,
    RegularSticker,
    RichReply,
    RichReplyReceipt,
    StickerFormat,
    StickerPart,
    StickerPartKind,
    StickerRequest,
    TargetRef,
    TransportReceipt,
)
from .kernel import InteractionKernel
from .stickers import SQLiteStickerCatalog, StickerCatalog
from .text import split_semantic_bubbles

__version__ = "0.1.0"

__all__ = [
    "BubbleRequest",
    "CallbackPayload",
    "CallbackRegistry",
    "CallbackRejection",
    "CallbackStore",
    "CallbackResolution",
    "CallbackToken",
    "ChoiceOption",
    "ChoicesRequest",
    "CompletionMode",
    "DeliveryStatus",
    "IncomingReaction",
    "IncomingSticker",
    "InteractionCapabilities",
    "InteractionHost",
    "InteractionKernel",
    "InteractionKind",
    "InteractionReceipt",
    "MiniAppHost",
    "MiniAppRequest",
    "ReactionRequest",
    "RegularSticker",
    "RichReply",
    "RichReplyReceipt",
    "SQLiteCallbackStore",
    "SQLiteStickerCatalog",
    "StickerCatalog",
    "StickerFormat",
    "StickerPart",
    "StickerPartKind",
    "StickerRequest",
    "TargetRef",
    "TransportReceipt",
    "split_semantic_bubbles",
]
